CREATE TABLE IF NOT EXISTS Customers (
    Id BIGINT AUTO_INCREMENT PRIMARY KEY,
    FullName VARCHAR(150) NOT NULL,
    Nickname VARCHAR(100) NULL,
    PhoneNumber VARCHAR(20) NULL,
    CurrentBalance DECIMAL(12,2) NOT NULL DEFAULT 0.00,
    CreatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
